version: '3.8'

services:

  backend:
    build: ./backend
    env_file: .env
    command: sh -c "python3 manage.py migrate && daphne -b 0.0.0.0 -p 8000 SPAComments.asgi:application"
    restart: always
    volumes:
      - static:/static
      - media:/media
      - ./backend:/app
    depends_on:
      - db

  frontend:
    build: ./frontend
    env_file: .env
    volumes:
      - ./frontend:/app
      - dist:/frontend/dist/

  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: $(POSTGRES_USER)
      POSTGRES_PASSWORD: $(POSTGRES_PASSWORD)
      POSTGRES_DB: $(POSTGRES_DB)
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  nginx:
    image: nginx:stable-alpine
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - static:/static
      - media:/media
      - dist:/frontend/dist
    depends_on:
      - backend
      - frontend

volumes:
  dist:
  media:
  static:
  db_data:
