version: '3.8'

services:

  backend:
    build: ./backend
    env_file: .env
    command: daphne -b 0.0.0.0 -p 8000 SPAComments.asgi:application
    restart: always
    volumes:
      - ./backend:/app
    depends_on:
      - db

  frontend:
    build: ./frontend
    env_file: .env
    volumes:
      - ./frontend:/app

  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: userdb
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: comments
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  nginx:
    image: nginx:stable-alpine
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./backend/static:/static
      - ./backend/media:/media
      - ./frontend/dist:/frontend
    depends_on:
      - backend
      - frontend

volumes:
  db_data:
